export enum ACTIONS {
  USERS_REQUEST_DATA = 'USERS_REQUEST_DATA',
  USERS_REQUEST_END = 'USERS_REQUEST_END',
  USERS_RECEIVE_DATA = 'USERS_RECEIVE_DATA',
  USERS_REJECT_DATA = 'USERS_REJECT_DATA',
  METRICS_REQUEST_DATA = 'METRICS_REQUEST_DATA',
  METRICS_REQUEST_END = 'METRICS_REQUEST_END',
  METRICS_RECEIVE_DATA = 'METRICS_RECEIVE_DATA',
  METRICS_REJECT_DATA = 'METRICS_REJECT_DATA',
}
